#!groovy

// Generated by IBM TransformationAdvisor
// Thu Nov 22 17:49:27 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytrader3ee6'
    mvnCommands = '--version'
    test='false'
}